# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bear Bites' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bear Bites
  pod "Parse"
  pod "AlamofireImage"
  pod "MessageInputBar"

  target 'Bear BitesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bear BitesUITests' do
    # Pods for testing
  end

end
